### ISSUE TITLE
deprecated each() on php 7.2

### ISSUE THREAD

**Issue by neomobil** [laravel-enso/MenuManager#8]
Hi!
There is a each() deprecated function in the file MenuBuilder.php
It breaks the app partially because of no children menus are appended.

**Comment by aocneanu** [comment]
Hi,

Deprecated how?

The only ‘each()’ I see in the builder is the one that iterates a Laravel collection.. could you provide more info?

**Comment by neomobil** [comment]
I'm trying to debug a copy of laravel-enso on a newly installed vagrant/homestead actually with PHP 7.2.
I'm not able to get the child menus of Administration and System menus. 
This what i get:
`
menus": [
{
"id": 1,
"icon": "fa fa-fw fa-tachometer",
"link": "dashboard.index",
"name": "Dashboard",
"parent_id": null,
"has_children": false,
"children": [],
"expanded": false,
"pivot": {
"role_id": "1",
"menu_id": "1",
"created_at": "2018-01-25 18:06:14.807",
"updated_at": "2018-01-25 18:06:14.807"
}
},
{
"id": 2,
"icon": "fa fa-fw fa-cogs",
"link": null,
"name": "Administration",
"parent_id": null,
"has_children": true,
"children": [],
"expanded": false,
"pivot": {
"role_id": "1",
"menu_id": "2",
"created_at": "2018-01-25 18:06:14.813",
"updated_at": "2018-01-25 18:06:14.813"
}
},
{
"id": 3,
"icon": "fa fa-fw fa-sliders",
"link": null,
"name": "System",
"parent_id": null,
"has_children": true,
"children": [],
"expanded": false,
"pivot": {
"role_id": "1",
"menu_id": "3",
"created_at": "2018-01-25 18:06:14.817",
"updated_at": "2018-01-25 18:06:14.817"
}
},
{
"id": 13,
"icon": "fa fa-fw fa-cloud-upload",
"link": "import.index",
"name": "Data Import",
"parent_id": null,
"has_children": false,
"children": [],
"expanded": false,
"pivot": {
"role_id": "1",
"menu_id": "13",
"created_at": "2018-01-25 18:06:15.093",
"updated_at": "2018-01-25 18:06:15.093"
}
}
],
`

**Comment by aocneanu** [comment]
Ah ok, from what I see, `role_id` is a string, not an integeer. This will happen also for `parent_id`, the key needed for building the nested menu. On line 27 in `MenuBuilder` we have a strict equality comparison ``if ($menu->parent_id === $parentId) {` and this breaks it for you.

In the database the column should be int

![image](https://user-images.githubusercontent.com/16073274/35426922-1ffc9f98-026f-11e8-92a6-68079b6132fb.png)

This could happen if you are using sqlite, or something else is messed in you db driver. 

If you're using sqlite then.. why would you? :)

**Comment by neomobil** [comment]
Hi!
Sorry for the inconvenience, and a BIG Thank you for your quick answer!
I'm using for this project SQL Server. I really don't like it, but this is a must for my customer.
Do you think also, to cast the parent_id and role_id in the Model could be a good way to solve the problem?

**Comment by neomobil** [comment]
Also I would recommend to build the menu maybe on another way.
Like so:
Create a `children` relation to the Menu
```
public function children() {
        return $this->hasMany(self::class ,'parent_id','id') ;
    }
```
then in the Menu Model
```protected` $with=['children'];```
and
in the getMenus method of the StateBuilder class
return $menus;
//return (new MenuBuilder($menus))->get();

It makes same output but without recursive looping.
What do you mean?

**Comment by aocneanu** [comment]
So,

1st, casting the attribute would fix the problem, but I'd rather not cast an attribute that is supposed to be int as int ..
You can always fork the repo and manage this locally.

But first check https://stackoverflow.com/questions/31563747/laravel-pdo-settings

2nd, I will add a children relation, because why not:)
I like the `$with` protected attribute also, but it won't do too much good in our case because:

Take account that we can have at least 3 levels of nesting on the current FE layout (on the backed, there is no limit). 

Let's take the current `System` menu. When we edit this menu and load it from BE to show it in the form, we don't need another 6 or so models loaded automatically. Imagine a complex app with maybe 30 menus nested on three levels.

We can go around this and still using the `children` relation and eager loading recursively in the `MenuBuilder` class. 

But this won't help either, because the menus are rendered based on the role's permissions. This is why this method receives a specific collection of menus, and builds the tree from that. We don't want all the roles to have access and view all the menus.

**Comment by neomobil** [comment]
Thank you again!
Your answers are really helpful!

Takó Kornél

www.neomobil.hu



2018-01-26 12:10 GMT+01:00 Adrian Ocneanu <notifications@github.com>:
